apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - msvc-bp-prod-api-cm0-configmap.yaml
  - msvc-bp-prod-api-deployment.yaml
  - msvc-bp-prod-api-service.yaml
  - msvc-bp-prod-db-deployment.yaml
  - msvc-bp-prod-db-service.yaml
  - msvc-prod-db-persistentvolumeclaim.yaml
  - msvc-bp-prod-api-ingress.yaml