apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\laura\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f compose.prod.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: msvc-bp-prod-db
  name: msvc-bp-prod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msvc-bp-prod-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\laura\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f compose.prod.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: msvc-bp-prod-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: msvc-prod
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:8.4.4
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          name: msvc-bp-prod-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: msvc-prod-db
      restartPolicy: Always
      volumes:
        - name: msvc-prod-db
          persistentVolumeClaim:
            claimName: msvc-prod-db
