apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "musiceventfinder.fullname" . }}-env
  labels:
    {{- include "musiceventfinder.labels" . | nindent 4 }}
data:
  DB_ROOT_PASSWORD: {{ .Values.api.env.dbRootPassword | quote }}